/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.
 
 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
 // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void strassenButton_click1(GButton source, GEvent event) { //_CODE_:strasseButton:405466:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:strasseButton:405466:

public void bahnButton_click1(GButton source, GEvent event) { //_CODE_:bahnButton:790158:
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:bahnButton:790158:

public void industrieButton_click1(GButton source, GEvent event) { //_CODE_:industrieButton:809355:
  println("button5 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:industrieButton:809355:

public void schienenButton_click1(GButton source, GEvent event) { //_CODE_:schienenButton:755053:
  println("button6 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:schienenButton:755053:

public void flucghafenButton_click1(GButton source, GEvent event) { //_CODE_:flughafenButton:424029:
  println("button7 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:flughafenButton:424029:

public void startseite_click1(GButton source, GEvent event) { //_CODE_:Startseite:483799:
  println("Startseite - GButton >> GEvent." + event + " @ " + millis());
  secondShow = true;
  PanMapEvent panMapEvent = new PanMapEvent(this, mapDetail.getId());
  panMapEvent.setToLocation(koelnLocation);
  eventDispatcher.fireMapEvent(panMapEvent);

  ZoomMapEvent zoomMapEvent = new ZoomMapEvent(this, mapDetail.getId(), ZoomMapEvent.ZOOM_TO_LEVEL);
  zoomMapEvent.setZoomLevel(koelnZoomLevel);
  zoomMapEvent.setTransformationCenterLocation(koelnLocation);
  eventDispatcher.fireMapEvent(zoomMapEvent);

  Startseite.setVisible(false);
  bahnButton.setVisible(true);
  strasseButton.setVisible(true);
  schienenButton.setVisible(true);
  industrieButton.setVisible(true);
  flughafenButton.setVisible(true);
} //_CODE_:Startseite:483799:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI() {
  G4P.messagesEnabled(true);
  G4P.setGlobalColorScheme(GCScheme.CYAN_SCHEME);
  G4P.setCursor(HAND);
  surface.setTitle("sketchProj");
  strasseButton = new GButton(this, 190, 30, 110, 20);
  strasseButton.setText("Strasse");
  strasseButton.addEventHandler(this, "strassenButton_click1");
  bahnButton = new GButton(this, 30, 30, 110, 20);
  bahnButton.setText("Bahn");
  bahnButton.addEventHandler(this, "bahnButton_click1");
  industrieButton = new GButton(this, 500, 30, 110, 20);
  industrieButton.setText("Industrie");
  industrieButton.addEventHandler(this, "industrieButton_click1");
  schienenButton = new GButton(this, 340, 30, 110, 20);
  schienenButton.setText("Schienen");
  schienenButton.addEventHandler(this, "schienenButton_click1");
  flughafenButton = new GButton(this, 660, 30, 110, 20);
  flughafenButton.setText("Info");
  flughafenButton.addEventHandler(this, "flucghafenButton_click1");
  Startseite = new GButton(this, 700, 560, 80, 30);
  Startseite.setText("Startseite");
  Startseite.addEventHandler(this, "startseite_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton strasseButton; 
GButton bahnButton; 
GButton industrieButton; 
GButton schienenButton; 
GButton flughafenButton; 
GButton Startseite;